services:
  cgate_DB:
    env_file:
      - .env
    container_name: cgateDB #cgate_Db -> cgateDB
    image: mysql:8.4
    ports:
      - '3310:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ='Asia/Seoul'
    networks:
      - cgate_network
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    container_name: cgateAdminer  #cgate_adminer => cgateAdminer
    networks:
      - cgate_network
    image: adminer
    ports:
      - '8082:8080'
    restart: unless-stopped

networks:
  cgate_network:
    driver: bridge
